//
// D:/Engine-Graphics/src/graphics/ispc/image_processing_ispc.h
// (Header automatically generated by the ispc compiler.)
// DO NOT EDIT THIS FILE.
//

#ifndef ISPC_D__ENGINE_GRAPHICS_SRC_GRAPHICS_ISPC_IMAGE_PROCESSING_ISPC_H
#define ISPC_D__ENGINE_GRAPHICS_SRC_GRAPHICS_ISPC_IMAGE_PROCESSING_ISPC_H

#include <stdint.h>


#ifdef __cplusplus
namespace ispc
{      /* namespace */
#endif // __cplusplus

#ifndef __ISPC_ALIGN__
#if defined(__clang__) || !defined(_MSC_VER)
// Clang, GCC, ICC
#define __ISPC_ALIGN__(s) __attribute__((aligned(s)))
#define __ISPC_ALIGNED_STRUCT__(s) struct __ISPC_ALIGN__(s)
#else
// Visual Studio
#define __ISPC_ALIGN__(s) __declspec(align(s))
#define __ISPC_ALIGNED_STRUCT__(s) __ISPC_ALIGN__(s) struct
#endif
#endif

#ifndef __ISPC_STRUCT_Color__
#define __ISPC_STRUCT_Color__
	struct Color
	{
		float r_;
		float g_;
		float b_;
		float a_;
	};
#endif

#ifndef __ISPC_STRUCT_Color_R8G8B8A8__
#define __ISPC_STRUCT_Color_R8G8B8A8__
	struct Color_R8G8B8A8
	{
		uint8_t r_;
		uint8_t g_;
		uint8_t b_;
		uint8_t a_;
	};
#endif


///////////////////////////////////////////////////////////////////////////
// Functions exported from ispc code
///////////////////////////////////////////////////////////////////////////
#if defined(__cplusplus) && (!defined(__ISPC_NO_EXTERN_C) || !__ISPC_NO_EXTERN_C)
	extern "C" {
#endif // __cplusplus
	extern void ImageProc_Downsample2x(int32_t w, int32_t h, const struct Color* input, struct Color* output);
	extern void ImageProc_GammaToLinear(int32_t w, int32_t h, const struct Color* input, struct Color* output);
	extern void ImageProc_LinearToGamma(int32_t w, int32_t h, const struct Color* input, struct Color* output);
	extern void ImageProc_Pack_R8G8B8A8(int32_t numTexels, const struct Color* input, struct Color_R8G8B8A8* output);
	extern void ImageProc_Unpack_R8G8B8A8(int32_t numTexels, const struct Color_R8G8B8A8* input, struct Color* output);
#if defined(__cplusplus) && (!defined(__ISPC_NO_EXTERN_C) || !__ISPC_NO_EXTERN_C)
	}  /* end extern C */
#endif // __cplusplus


#ifdef __cplusplus
} /* namespace */
#endif // __cplusplus

#endif // ISPC_D__ENGINE_GRAPHICS_SRC_GRAPHICS_ISPC_IMAGE_PROCESSING_ISPC_H
