#pragma once

#include "core/types.h"

namespace Client
{
	/**
	 * Scan codes. Based on SDL2's scancodes.
	 */
	enum class ScanCode
	{
		UNKNOWN = 0,

		CHAR_A = 4,
		CHAR_B = 5,
		CHAR_C = 6,
		CHAR_D = 7,
		CHAR_E = 8,
		CHAR_F = 9,
		CHAR_G = 10,
		CHAR_H = 11,
		CHAR_I = 12,
		CHAR_J = 13,
		CHAR_K = 14,
		CHAR_L = 15,
		CHAR_M = 16,
		CHAR_N = 17,
		CHAR_O = 18,
		CHAR_P = 19,
		CHAR_Q = 20,
		CHAR_R = 21,
		CHAR_S = 22,
		CHAR_T = 23,
		CHAR_U = 24,
		CHAR_V = 25,
		CHAR_W = 26,
		CHAR_X = 27,
		CHAR_Y = 28,
		CHAR_Z = 29,

		NUM_1 = 30,
		NUM_2 = 31,
		NUM_3 = 32,
		NUM_4 = 33,
		NUM_5 = 34,
		NUM_6 = 35,
		NUM_7 = 36,
		NUM_8 = 37,
		NUM_9 = 38,
		NUM_0 = 39,

		RETURN = 40,
		ESCAPE = 41,
		BACKSPACE = 42,
		TAB = 43,
		SPACE = 44,

		MINUS = 45,
		EQUALS = 46,
		LEFTBRACKET = 47,
		RIGHTBRACKET = 48,
		BACKSLASH = 49,
		NONUSHASH = 50,
		SEMICOLON = 51,
		APOSTROPHE = 52,
		GRAVE = 53,
		COMMA = 54,
		PERIOD = 55,
		SLASH = 56,

		CAPSLOCK = 57,

		F1 = 58,
		F2 = 59,
		F3 = 60,
		F4 = 61,
		F5 = 62,
		F6 = 63,
		F7 = 64,
		F8 = 65,
		F9 = 66,
		F10 = 67,
		F11 = 68,
		F12 = 69,

		PRINTSCREEN = 70,
		SCROLLLOCK = 71,
		PAUSE = 72,
		INSERT = 73,
		HOME = 74,
		PAGEUP = 75,
		DELETE = 76,
		END = 77,
		PAGEDOWN = 78,
		RIGHT = 79,
		LEFT = 80,
		DOWN = 81,
		UP = 82,

		NUMLOCKCLEAR = 83,
		KP_DIVIDE = 84,
		KP_MULTIPLY = 85,
		KP_MINUS = 86,
		KP_PLUS = 87,
		KP_ENTER = 88,
		KP_1 = 89,
		KP_2 = 90,
		KP_3 = 91,
		KP_4 = 92,
		KP_5 = 93,
		KP_6 = 94,
		KP_7 = 95,
		KP_8 = 96,
		KP_9 = 97,
		KP_0 = 98,
		KP_PERIOD = 99,

		LCTRL = 224,
		LSHIFT = 225,
		LALT = 226, /**< alt, option */
		LGUI = 227, /**< windows, command (apple), meta */
		RCTRL = 228,
		RSHIFT = 229,
		RALT = 230, /**< alt gr, option */
		RGUI = 231, /**< windows, command (apple), meta */
	};

	static const i32 SCAN_CODE_BIT = (1 << 30);
#define SCANCODE_TO_KEYCODE(CODE) (KeyCode)((i32)CODE | SCAN_CODE_BIT)

	/**
	 * Key codes. Based on SDL2's key codes.
	 */
	enum class KeyCode : i32
	{
		UNKNOWN = 0,
		RETURN = '\r',
		ESCAPE = '\033',
		BACKSPACE = '\b',
		TAB = '\t',
		SPACE = ' ',
		EXCLAIM = '!',
		QUOTEDBL = '"',
		HASH = '#',
		PERCENT = '%',
		DOLLAR = '$',
		AMPERSAND = '&',
		QUOTE = '\'',
		LEFTPAREN = '(',
		RIGHTPAREN = ')',
		ASTERISK = '*',
		PLUS = '+',
		COMMA = ',',
		MINUS = '-',
		PERIOD = '.',
		SLASH = '/',
		NUM_0 = '0',
		NUM_1 = '1',
		NUM_2 = '2',
		NUM_3 = '3',
		NUM_4 = '4',
		NUM_5 = '5',
		NUM_6 = '6',
		NUM_7 = '7',
		NUM_8 = '8',
		NUM_9 = '9',
		COLON = ':',
		SEMICOLON = ';',
		LESS = '<',
		EQUALS = '=',
		GREATER = '>',
		QUESTION = '?',
		AT = '@',

		LEFTBRACKET = '[',
		BACKSLASH = '\\',
		RIGHTBRACKET = ']',
		CARET = '^',
		UNDERSCORE = '_',
		BACKQUOTE = '`',
		CHAR_a = 'a',
		CHAR_b = 'b',
		CHAR_c = 'c',
		CHAR_d = 'd',
		CHAR_e = 'e',
		CHAR_f = 'f',
		CHAR_g = 'g',
		CHAR_h = 'h',
		CHAR_i = 'i',
		CHAR_j = 'j',
		CHAR_k = 'k',
		CHAR_l = 'l',
		CHAR_m = 'm',
		CHAR_n = 'n',
		CHAR_o = 'o',
		CHAR_p = 'p',
		CHAR_q = 'q',
		CHAR_r = 'r',
		CHAR_s = 's',
		CHAR_t = 't',
		CHAR_u = 'u',
		CHAR_v = 'v',
		CHAR_w = 'w',
		CHAR_x = 'x',
		CHAR_y = 'y',
		CHAR_z = 'z',

		CAPSLOCK = SCANCODE_TO_KEYCODE(ScanCode::CAPSLOCK),
		F1 = SCANCODE_TO_KEYCODE(ScanCode::F1),
		F2 = SCANCODE_TO_KEYCODE(ScanCode::F2),
		F3 = SCANCODE_TO_KEYCODE(ScanCode::F3),
		F4 = SCANCODE_TO_KEYCODE(ScanCode::F4),
		F5 = SCANCODE_TO_KEYCODE(ScanCode::F5),
		F6 = SCANCODE_TO_KEYCODE(ScanCode::F6),
		F7 = SCANCODE_TO_KEYCODE(ScanCode::F7),
		F8 = SCANCODE_TO_KEYCODE(ScanCode::F8),
		F9 = SCANCODE_TO_KEYCODE(ScanCode::F9),
		F10 = SCANCODE_TO_KEYCODE(ScanCode::F10),
		F11 = SCANCODE_TO_KEYCODE(ScanCode::F11),
		F12 = SCANCODE_TO_KEYCODE(ScanCode::F12),
		PRINTSCREEN = SCANCODE_TO_KEYCODE(ScanCode::PRINTSCREEN),
		SCROLLLOCK = SCANCODE_TO_KEYCODE(ScanCode::SCROLLLOCK),
		PAUSE = SCANCODE_TO_KEYCODE(ScanCode::PAUSE),
		INSERT = SCANCODE_TO_KEYCODE(ScanCode::INSERT),
		HOME = SCANCODE_TO_KEYCODE(ScanCode::HOME),
		PAGEUP = SCANCODE_TO_KEYCODE(ScanCode::PAGEUP),
		DELETE = '\177',
		END = SCANCODE_TO_KEYCODE(ScanCode::END),
		PAGEDOWN = SCANCODE_TO_KEYCODE(ScanCode::PAGEDOWN),
		RIGHT = SCANCODE_TO_KEYCODE(ScanCode::RIGHT),
		LEFT = SCANCODE_TO_KEYCODE(ScanCode::LEFT),
		DOWN = SCANCODE_TO_KEYCODE(ScanCode::DOWN),
		UP = SCANCODE_TO_KEYCODE(ScanCode::UP),
		NUMLOCKCLEAR = SCANCODE_TO_KEYCODE(ScanCode::NUMLOCKCLEAR),
		KP_DIVIDE = SCANCODE_TO_KEYCODE(ScanCode::KP_DIVIDE),
		KP_MULTIPLY = SCANCODE_TO_KEYCODE(ScanCode::KP_MULTIPLY),
		KP_MINUS = SCANCODE_TO_KEYCODE(ScanCode::KP_MINUS),
		KP_PLUS = SCANCODE_TO_KEYCODE(ScanCode::KP_PLUS),
		KP_ENTER = SCANCODE_TO_KEYCODE(ScanCode::KP_ENTER),
		KP_1 = SCANCODE_TO_KEYCODE(ScanCode::KP_1),
		KP_2 = SCANCODE_TO_KEYCODE(ScanCode::KP_2),
		KP_3 = SCANCODE_TO_KEYCODE(ScanCode::KP_3),
		KP_4 = SCANCODE_TO_KEYCODE(ScanCode::KP_4),
		KP_5 = SCANCODE_TO_KEYCODE(ScanCode::KP_5),
		KP_6 = SCANCODE_TO_KEYCODE(ScanCode::KP_6),
		KP_7 = SCANCODE_TO_KEYCODE(ScanCode::KP_7),
		KP_8 = SCANCODE_TO_KEYCODE(ScanCode::KP_8),
		KP_9 = SCANCODE_TO_KEYCODE(ScanCode::KP_9),
		KP_0 = SCANCODE_TO_KEYCODE(ScanCode::KP_0),
		KP_PERIOD = SCANCODE_TO_KEYCODE(ScanCode::KP_PERIOD),

		LCTRL = SCANCODE_TO_KEYCODE(ScanCode::LCTRL),
		LSHIFT = SCANCODE_TO_KEYCODE(ScanCode::LSHIFT),
		LALT = SCANCODE_TO_KEYCODE(ScanCode::LALT),
		LGUI = SCANCODE_TO_KEYCODE(ScanCode::LGUI),
		RCTRL = SCANCODE_TO_KEYCODE(ScanCode::RCTRL),
		RSHIFT = SCANCODE_TO_KEYCODE(ScanCode::RSHIFT),
		RALT = SCANCODE_TO_KEYCODE(ScanCode::RALT),
		RGUI = SCANCODE_TO_KEYCODE(ScanCode::RGUI),
	};
#undef SCANCODE_TO_KEYCODE

} // namespace Client
